language: node_js
node_js:
- "5"
install:
- npm install -g elm
- npm install -g elm-format@0.7.0-exp
- npm install -g elm-test
- elm-package install -y
- pushd tests && elm-package install -y && popd
- elm-format --validate src/ tests/Tests/
script:
- elm-test
